name: Check Files

on: push

jobs:
  lint:
    name: lint some codes here
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v4

      - name: Run a Lint
        uses: super-linter/super-linter@v5.6.1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GTIHUB_TOKEN }}

